name: Linux CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker image
      run: docker build . --file AppImage/docker/Dockerfile --tag build-vkquake
    - name: Build vkQuake
      run: docker run --rm --privileged -v ${PWD}:/usr/src/vkQuake build-vkquake /usr/src/vkQuake/AppImage/run-in-docker.sh
    - name: Upload vkQuake
      uses: actions/upload-artifact@v2
      with:
        name: vkquake_linux64.tar.gz
        path: AppImage/vkquake_linux64.tar.gz
